spring.application.name=digitalfix-ms-bff
# Emisor de tokens v2 del tenant DigitalFix
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/762b016c-dc33-4db0-ad42-44f32afe71f4/v2.0

# Identificador de DigitalFix API: audiencia esperada del access token
spring.security.oauth2.resourceserver.jwt.audiences=85329d90-58f8-4317-a820-452599b3b04c